language: csharp
solution: bill-payments-dotnet-sdk.sln
install:
- nuget restore bill-payments-dotnet-sdk.sln
- nuget install NUnit.Runners -OutputDirectory testrunner
- if [[ $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_BRANCH = 'master' ]]; then openssl aes-256-cbc -K $encrypted_35f90653928635e2_key -iv $encrypted_35f90653928635e2_iv -in Qiwi.BillPayments.Tests/App.config.enc -out Qiwi.BillPayments.Tests/App.config -d; fi
script:
- xbuild bill-payments-dotnet-sdk.sln /p:Configuration=Release
- mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Qiwi.BillPayments.Tests/bin/Release/netcoreapp2.0/Qiwi.BillPayments.Tests.dll
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./Qiwi.BillPayments.*.nupkg -Verbosity detailed -ApiKey $ApiKey -Source https://api.nuget.org/v3/index.json
  on:
    tags: true
    branches:
      only:
        - master
