language: csharp
mono: none
dotnet: 2.1.500
install:
- if [[ $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_BRANCH = 'master' ]]; then openssl aes-256-cbc -K $encrypted_35f90653928635e2_key -iv $encrypted_35f90653928635e2_iv -in Qiwi.BillPayments.Tests/App.config.enc -out Qiwi.BillPayments.Tests/App.config -d; fi
script:
- dotnet test -c Release bill-payments-dotnet-sdk.sln
